# Site settings
title: Robert Laws - Librarian & Web Developer / Professional Showcase and Blog
tagline: Librarian & Web Developer
description: > # this means to ignore newlines until "baseurl:"
  Robert Laws - Librarian & Web Developer / Professional Showcase and Blog
email: roblaws@me.com
twitter_username: robdlaws
github_username: robert-laws
learn_profile: robert-laws
email_username: roblaws@me.com
copyright_name: robert-laws

baseurl: '' # the subpath of your site, e.g. /blog
url: https://robert-laws.com
excerpt_separator: <!-- more -->

# Timezone
timezone: 'Asia/Riyadh'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title

# Files to Exclude from Build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - fonts/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-autoprefixer

# Collections
collections_dir: my_collections
collections:
  projects:
    output: true
  developer_portfolio:
    output: true
    permalink: /project/developer-portfolio/:name
  dog_daycare:
    output: true
    permalink: /project/dog-daycare/:name
  instruction_menu:
    output: true
    permalink: /project/instruction-menu/:name
  restaurant_explorer:
    output: true
    permalink: /project/restaurant-explorer/:name
  library_website:
    output: true
    permalink: /project/library-website/:name
  checkmark_list:
    output: true
    permalink: /project/checkmark-list/:name
  data_viz_cafe:
    output: true
    permalink: /project/data-viz-cafe/:name
  lesson_builder:
    output: true
    permalink: /project/lesson-builder/:name
  primary_sources:
    output: true
    permalink: /project/primary-sources/:name
  creativity:
    output: true
    permalink: /project/creativity

# Front Matter Defaults
defaults:
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'project'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'Robert Laws'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  - scope:
      path: 'assets/img'
    values:
      image: true
